#!/bin/sh

# Create dist file
./dist

# Find it
ARCHIVE=$(ls *.orig.tar.gz)

# Sign the archive
gpg --sign --armor --detach-sign *.orig.tar.gz

# Extract dist file in temp dir
T=$(mktemp -d)
mv *.orig.tar.gz.asc *.orig.tar.gz $T
cd $T
tar -xvvf *tar.gz
cd -

# Path for source
UNCOMPRESSED=$(realpath $T/lapdog)

# Copy debian/ directory in the source dir
git stash
git checkout debian
cp -r debian/ $UNCOMPRESSED/
git checkout -
git stash pop

# Make debian package
cd $UNCOMPRESSED
dpkg-buildpackage
lintian --pedantic -E --color auto -i -I ../*.dsc
echo $UNCOMPRESSED
